### ISSUE TITLE
Fix std.time.timestamp() compatibility with Zig 0.16+

### ISSUE THREAD

**Issue by AnthemFlynn** [AnthemFlynn/Kairoz#4]
## Bug Report

The `today()` function in `src/Date.zig` fails to compile with Zig 0.16+ because `std.time.timestamp()` no longer exists.

### Error

```
error: struct 'time' has no member named 'timestamp'
    const ts = std.time.timestamp();
```

### Fix

Replace `std.time.timestamp()` with `std.posix.gettimeofday()`:

```zig
pub fn today() Date {
    var tv: std.posix.timeval = undefined;
    std.posix.gettimeofday(&tv, null);
    return epochDaysToDate(@intCast(@divFloor(tv.sec, 86400)));
}
```

### Context

This blocks integration of Kairoz into projects using Zig 0.16.0-dev.1912+.
